project_id = "gsvkwedgiwwvnroghbzr"

[functions.gmail-auth]
verify_jwt = false

[functions.gmail-scan]
verify_jwt = false

[functions.extension-sync]
verify_jwt = false

[functions.send-notification]
verify_jwt = false
